# Generated by Django 4.0.6 on 2022-07-25 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty_value', models.CharField(choices=[('0', '0'), ('FoodGrains', (('1Kg', '1Kg'), ('2Kg', '2Kg'), ('5Kg', '5Kg'), ('10Kg', '10Kg')))], default='0', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category_item',
            field=models.CharField(choices=[('None', 'None'), ('FoodGrains', 'FoodGrains'), ('Oils', 'Oils'), ('Fruits & Veg', 'Fruits & Veg'), ('Snacks', 'Snacks'), ('Dairy Products', 'Dairy Products'), ('Personal Care', 'Personal Care')], default='None', max_length=50),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('Item_qty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.variant')),
                ('Item_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ratings')),
                ('Item_reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reviews')),
            ],
        ),
    ]
