# Generated by Django 4.0.6 on 2022-07-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_created_at_alter_order_order_id_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_name',
            field=models.CharField(max_length=100),
        ),
    ]
