# Generated by Django 4.0.6 on 2022-07-26 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_cartitem_payment_delete_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Item_rating',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Item_reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating_item',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_item',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('FoodGrains', 'FoodGrains'), ('Oils', 'Oils'), ('Fruits & Veg', 'Fruits & Veg'), ('Snacks', 'Snacks'), ('Dairy Products', 'Dairy Products'), ('Personal Care', 'Personal Care')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_qty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.variant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviews_item',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad')], default='None', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='Qty_value',
            field=models.CharField(blank=True, choices=[('0', '0'), ('FoodGrains', (('1Kg', '1Kg'), ('2Kg', '2Kg'), ('5Kg', '5Kg'), ('10Kg', '10Kg'))), ('Oils', (('1L', '1L'), ('2L', '2L'), ('5L', '5L'), ('10L', '10L'))), ('Fruits & Veg', (('1Kg', '1Kg'), ('2Kg', '2Kg'), ('5Kg', '5Kg'), ('10Kg', '10Kg'))), ('Snacks', (('100gm', '100gm'), ('200gm', '200gm'), ('500gm', '500gm'), ('750gm', '750gm'))), ('Dairy Products', (('1L', '1L'), ('2L', '2L'), ('5L', '5L'), ('10L', '10L'))), ('Personal Care', (('1', '1'), ('2', '2'), ('5', '5'), ('10', '10')))], default='0', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
