# Generated by Django 4.0.6 on 2022-07-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_item_item_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Item_qty',
        ),
        migrations.AddField(
            model_name='item',
            name='Units',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '10cm'), ('2', '20cm'), ('3', '50cm'), ('4', '100cm')], default='None', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Volumes',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1L'), ('2', '2L'), ('3', '5L'), ('4', '10L')], default='None', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Weights',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1Kg'), ('2', '2Kg'), ('3', '5Kg'), ('4', '10Kg')], default='None', max_length=50, null=True),
        ),
    ]
