# Generated by Django 4.0.6 on 2022-07-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_item_item_qty_item_units_item_volumes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='app.item'),
        ),
    ]
