# Generated by Django 4.0.6 on 2022-07-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_cartitem_item_cartitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviews_item',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('0', 'Excellent'), ('1', 'Good'), ('2', 'Average'), ('3', 'Bad')], default='None', max_length=10, null=True),
        ),
    ]
