# Generated by Django 4.0.6 on 2022-07-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_reviews_reviews_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_max_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
